// <auto-generated />
using System;
using BS2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BS2.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004110547_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("banksync")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BS2.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("text")
                        .HasColumnName("external_account_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identifier");

                    b.Property<string>("IdentifierHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("identifier_hash");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("BankConnectionId")
                        .HasDatabaseName("ix_accounts_bank_connection_id");

                    b.HasIndex("UserId", "IdentifierHash")
                        .IsUnique()
                        .HasDatabaseName("ix_accounts_user_id_identifier_hash");

                    b.ToTable("accounts", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.BankConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("bank_name");

                    b.Property<string>("ConfiguredIbansRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("configured_ibans_raw");

                    b.Property<int?>("ConsentValidityDays")
                        .HasColumnType("integer")
                        .HasColumnName("consent_validity_days");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalSessionId")
                        .HasColumnType("text")
                        .HasColumnName("external_session_id");

                    b.Property<DateTime?>("LastAuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authorized_at");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_sync_error");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("provider");

                    b.Property<string>("PsuType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("psu_type");

                    b.Property<bool>("SelectAccountsAtBank")
                        .HasColumnType("boolean")
                        .HasColumnName("select_accounts_at_bank");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_bank_connections");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bank_connections_user_id");

                    b.HasIndex("UserId", "Provider", "BankName")
                        .IsUnique()
                        .HasDatabaseName("ix_bank_connections_user_id_provider_bank_name");

                    b.ToTable("bank_connections", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.ToTable("categories", "banksync");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Clothes",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Clothes",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "Communication",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Communication",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "Education",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Education",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "FoodAndDrink",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Food and drink (other)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "Groceries",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Groceries",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 6,
                            Code = "Health",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Health",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 7,
                            Code = "Home",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Home",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 8,
                            Code = "Activities",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Activities",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 9,
                            Code = "Chiro",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Chiro",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 10,
                            Code = "Cycling",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Cycling",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 11,
                            Code = "Sports",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Sports",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 12,
                            Code = "Subscriptions",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Subscriptions",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 13,
                            Code = "Takeaway",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Takeaway",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 14,
                            Code = "Transport",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Transport",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 15,
                            Code = "FastFood",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Fast food",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = 16,
                            Code = "Gifts",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Gifts",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = 17,
                            Code = "Donations",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Donations",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = 18,
                            Code = "Drinks",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Drinks",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = 19,
                            Code = "Gadgets",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Gadgets",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = 20,
                            Code = "Games",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Games",
                            SortOrder = 19
                        },
                        new
                        {
                            Id = 21,
                            Code = "Restaurants",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Restaurants",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = 22,
                            Code = "Shows",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Shows",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = 23,
                            Code = "Travel",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Travel",
                            SortOrder = 22
                        },
                        new
                        {
                            Id = 24,
                            Code = "BankServices",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Bank services",
                            SortOrder = 23
                        },
                        new
                        {
                            Id = 25,
                            Code = "Fines",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Fines",
                            SortOrder = 24
                        },
                        new
                        {
                            Id = 26,
                            Code = "Cash",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Cash",
                            SortOrder = 25
                        },
                        new
                        {
                            Id = 27,
                            Code = "Investments",
                            IsActive = true,
                            Kind = "Transfer",
                            Name = "Investments",
                            SortOrder = 26
                        },
                        new
                        {
                            Id = 28,
                            Code = "Transfer",
                            IsActive = true,
                            Kind = "Transfer",
                            Name = "Transfer",
                            SortOrder = 27
                        },
                        new
                        {
                            Id = 29,
                            Code = "Vouchers",
                            IsActive = true,
                            Kind = "Income",
                            Name = "Vouchers",
                            SortOrder = 28
                        },
                        new
                        {
                            Id = 30,
                            Code = "Bonus",
                            IsActive = true,
                            Kind = "Income",
                            Name = "Bonus",
                            SortOrder = 29
                        },
                        new
                        {
                            Id = 31,
                            Code = "Wage",
                            IsActive = true,
                            Kind = "Income",
                            Name = "Wage",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = 32,
                            Code = "Taxes",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Taxes",
                            SortOrder = 31
                        },
                        new
                        {
                            Id = 33,
                            Code = "Reimbursement",
                            IsActive = true,
                            Kind = "Income",
                            Name = "Reimbursement",
                            SortOrder = 32
                        },
                        new
                        {
                            Id = 34,
                            Code = "Utilities",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Utilities",
                            SortOrder = 33
                        },
                        new
                        {
                            Id = 35,
                            Code = "Mortgage",
                            IsActive = true,
                            Kind = "Expense",
                            Name = "Mortgage",
                            SortOrder = 34
                        });
                });

            modelBuilder.Entity("BS2.Domain.Entities.ClassificationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Accepted")
                        .HasColumnType("boolean")
                        .HasColumnName("accepted");

                    b.Property<string>("AlternativesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("alternatives_json");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model");

                    b.Property<string>("PredictedCategoryCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("predicted_category_code");

                    b.Property<int?>("PredictedCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("predicted_category_id");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.Property<string>("UserPrompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_prompt");

                    b.HasKey("Id")
                        .HasName("pk_classification_runs");

                    b.HasIndex("PredictedCategoryId")
                        .HasDatabaseName("ix_classification_runs_predicted_category_id");

                    b.HasIndex("TransactionId", "CreatedAt")
                        .HasDatabaseName("ix_classification_runs_transaction_id_created_at");

                    b.ToTable("classification_runs", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_groups_user_id_name");

                    b.ToTable("groups", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.PendingAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BankConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_pending_authorizations");

                    b.HasIndex("BankConnectionId")
                        .HasDatabaseName("ix_pending_authorizations_bank_connection_id");

                    b.HasIndex("State")
                        .IsUnique()
                        .HasDatabaseName("ix_pending_authorizations_state");

                    b.ToTable("pending_authorizations", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.SyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ConnectionsSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("connections_skipped");

                    b.Property<int>("ConnectionsSynced")
                        .HasColumnType("integer")
                        .HasColumnName("connections_synced");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TransactionsClassified")
                        .HasColumnType("integer")
                        .HasColumnName("transactions_classified");

                    b.Property<int>("TransactionsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("transactions_fetched");

                    b.Property<int>("TransactionsNew")
                        .HasColumnType("integer")
                        .HasColumnName("transactions_new");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_sync_runs");

                    b.HasIndex("UserId", "StartedAt")
                        .HasDatabaseName("ix_sync_runs_user_id_started_at");

                    b.ToTable("sync_runs", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateOnly?>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("ClassificationSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("classification_source");

                    b.Property<DateTime?>("ClassifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("classified_at");

                    b.Property<string>("CounterpartyIban")
                        .HasColumnType("text")
                        .HasColumnName("counterparty_iban");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("counterparty_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("RawJson")
                        .HasColumnType("text")
                        .HasColumnName("raw_json");

                    b.Property<bool>("Reimbursed")
                        .HasColumnType("boolean")
                        .HasColumnName("reimbursed");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("AccountId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_transactions_account_id_external_id");

                    b.HasIndex("UserId", "CategoryId")
                        .HasDatabaseName("ix_transactions_user_id_category_id");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("ix_transactions_user_id_date");

                    b.ToTable("transactions", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.TransactionGroup", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TransactionId", "GroupId")
                        .HasName("pk_transaction_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_transaction_groups_group_id");

                    b.ToTable("transaction_groups", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth0Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("auth0subject");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0Subject")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0subject");

                    b.ToTable("users", "banksync");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Account", b =>
                {
                    b.HasOne("BS2.Domain.Entities.BankConnection", "BankConnection")
                        .WithMany("Accounts")
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_accounts_bank_connections_bank_connection_id");

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("BS2.Domain.Entities.ClassificationRun", b =>
                {
                    b.HasOne("BS2.Domain.Entities.Category", "PredictedCategory")
                        .WithMany()
                        .HasForeignKey("PredictedCategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_classification_runs_categories_predicted_category_id");

                    b.HasOne("BS2.Domain.Entities.Transaction", "Transaction")
                        .WithMany("ClassificationRuns")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_classification_runs_transactions_transaction_id");

                    b.Navigation("PredictedCategory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BS2.Domain.Entities.PendingAuthorization", b =>
                {
                    b.HasOne("BS2.Domain.Entities.BankConnection", "BankConnection")
                        .WithMany()
                        .HasForeignKey("BankConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_authorizations_bank_connections_bank_connection_id");

                    b.Navigation("BankConnection");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BS2.Domain.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("BS2.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BS2.Domain.Entities.TransactionGroup", b =>
                {
                    b.HasOne("BS2.Domain.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_groups_groups_group_id");

                    b.HasOne("BS2.Domain.Entities.Transaction", "Transaction")
                        .WithMany("Groups")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transaction_groups_transactions_transaction_id");

                    b.Navigation("Group");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BS2.Domain.Entities.BankConnection", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Group", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BS2.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("ClassificationRuns");

                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
